name: CI-CD-Pipeline-via-ssh
env:
  EB_PACKAGE_S3_BUCKET_NAME : "adv-it-flask-application-packages"
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIRONMENT_NAME       : "MyFlask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-west-2"

on: 
  push:
    branches: 
      - master

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
#     - name: Git clone our repo
#       uses: actions/checkout@v1
       
#     - name: Create ZIP deployment package
#       run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.TEST_KEY }} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        
    - name: executing remote ssh commands using ssh key 
      uses: appleboy/ssh-action@master 
      with: 
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }} 
        key: ${{ secrets.TEST_KEY }} 
        port: ${{ secrets.PORT }} 
        script: scp 123.txt ${{ secrets.SECURE_HOST_NAME }}:/home/ubuntu/
        
        
#     - name: ls -a via OPEN SSH Private Key
#       uses: garygrossgarten/github-action-ssh@release
#         with:
#           command: ls -a
#           host: ${{ secrets.HOST }}
#           username: garygrossgarten
#           password: ${{ secrets.PASSPHRASE }}
#           privateKey: ${{ secrets.PRIVATE_KEY}}
        
#     - name: Upload file via SSH
#       uses: nicklasfrahm/scp-action@main
#       with:
#         direction: upload
#         host: ${{ secrets.SSH_TARGET_HOST }}
#         fingerprint: ${{ secrets.SSH_TARGET_FINGERPRINT }}
#         username: ${{ secrets.SSH_USER }}
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         proxy_host: ${{ secrets.SSH_PROXY_HOST }}
#         proxy_fingerprint: ${{ secrets.SSH_PROXY_FINGERPRINT }}
#         proxy_username: ${{ secrets.SSH_USER }}
#         proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
#         source: |
#           path/to/source/a.txt
#           path/to/source/b.txt
#           target: path/to/target






