name: CI-CD-Pipeline-via-ssh
env:
  EB_PACKAGE_S3_BUCKET_NAME : "adv-it-flask-application-packages"
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIRONMENT_NAME       : "MyFlask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-west-2"

on: 
  push:
    branches: 
      - master

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
#     - name: Git clone our repo
#       uses: actions/checkout@v1
       
#     - name: Create ZIP deployment package
#       run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.TEST_KEY }} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        
    - name: executing remote ssh commands using ssh key 
      uses: appleboy/ssh-action@master 
      with: 
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }} 
        key: ${{ secrets.TEST_KEY }} 
        port: ${{ secrets.PORT }} 
        script: ls -la 






